    export const challenges = [
        { title: 'Drink Water', link: 'https://premforreal.github.io/frontend-mini-challenges/16.%20Drink%20Water/index.html' },
        { title: 'Theme Clock', link: 'https://premforreal.github.io/frontend-mini-challenges/19.%20Theme%20Clock/index.html' },
        { title: 'Progress Steps', link: 'https://premforreal.github.io/frontend-mini-challenges/2.%20Progress%20Steps/index.html' },
        { title: 'Sticky Navbar', link: 'https://premforreal.github.io/frontend-mini-challenges/25.%20Sticky%20Navbar/index.html' },
        { title: 'Toast Popup', link: 'https://premforreal.github.io/frontend-mini-challenges/27.%20Toast%20pop%20up/index.html' },
        { title: 'Github profiles', link: 'https://premforreal.github.io/frontend-mini-challenges/28.%20Github%20Profiles/index.html'},
        { title: 'Rotating Navigation', link: 'https://premforreal.github.io/frontend-mini-challenges/3.%20Rotating%20Navigation/index.html' },
        { title: 'Auto Text Effect', link: 'https://premforreal.github.io/frontend-mini-challenges/30.%20Auto%20Text%20Effect/index.html' },
        { title: 'Password Generator', link: 'https://premforreal.github.io/frontend-mini-challenges/31.%20Password%20Generator/index.html' },
        { title: 'Image Carousel', link: 'https://premforreal.github.io/frontend-mini-challenges/35.%20Image%20Carousel/index.html' },
        { title: 'Password Strength Background', link: 'https://premforreal.github.io/frontend-mini-challenges/39.%20Password%20Strength%20Background/index.html' },
        { title: 'Hidden Search Widget', link: 'https://premforreal.github.io/frontend-mini-challenges/4.%20Hidden%20Search%20Widget/index.html'},
        { title: 'Verfiy Account Ui', link: 'https://premforreal.github.io/frontend-mini-challenges/41.%20Verify%20Account%20UI/index.html' },
        { title: 'Custom Range Slider', link: 'https://premforreal.github.io/frontend-mini-challenges/44.%20Custom%20Range%20Slider/index.html' },
        { title: 'Blurry Loading Page', link: 'https://premforreal.github.io/frontend-mini-challenges/5.%20Blurry%20Loading%20Page/index.html' },
        { title: 'Scrolling Animation', link: 'https://premforreal.github.io/frontend-mini-challenges/6.%20Scrolling%20Animation/index.html' },
        { title: 'Form Wave Animation', link: 'https://premforreal.github.io/frontend-mini-challenges/8.%20Form%20Wave%20Animation/index.html' },
        { title: 'Guess The Number', link: 'https://premforreal.github.io/frontend-mini-challenges/Guess%20The%20Number/index.html'},    
    ];